### ISSUE TITLE
Why the `md_file.py` file crawl other GitHub repo beyond the link I gave.

### ISSUE THREAD

**Issue by alabulei1** [staru09/Gradio_bot#2]
I specified the repo to fetch in the command line, but from the log, the script is still fetching other repos.

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/91c74575-6a6e-43f3-9899-0391b3b631a6">

**Comment by alabulei1** [comment]
Another example:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/1084d460-5420-4f6f-9f34-055b8063438d">

**Comment by staru09** [comment]
The script prints the paths of all the folders and files it processes (e.g., `print(f"Processing {path}")`) as it crawls through the repository. However, in the output file, it only saves the content of markdown (`.md`) files found within these folders. While it may display messages about processing other file types (like `.go` files), these are merely being checked for the presence of markdown files and are not included in the output.

**Comment by alabulei1** [comment]
It's not the `.go` file. The problem is that the Python program crawls other repo's content. If you look at the screenshot I provided, you will find the Python program is crawling content from https://github.com/docker/docker and  https://github.com/capnproto.org/go, which is not expected.

**Comment by staru09** [comment]
I see it's because of the file structure of the repo that you are crawling 
https://github.com/cri-o/cri-o/tree/main/vendor/github.com/docker/docker/api
this repo has this directory inside the main folder ```vendor/github.com/docker/docker/api```
the screenshot that you attached starts with vendor followed by the link so it's actually not crawling some other repo.

**Comment by alabulei1** [comment]
Oh, I understand now. When I replaced `vendor/github.com/docker/docker` with `https://github.com/docker/docker`, the new link worked correctly. That’s why I initially thought it was from other repositories. Thank you so much for clarifying!
